name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Deploy to EC2 Instance
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_HOST }}
          EC2_USER: ${{ secrets.USER_NAME }}
          APP_DIR: /home/ubuntu/proyecto_flask  
          APP_FILE: aplicacion_flask.py
          ENVIRONMENT: production
      
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
              # Acceder al directorio del proyecto
              cd $APP_DIR &&

              # Activar el entorno virtual
              source venv/bin/activate &&

              # Actualizar el código desde la rama dev
              git fetch --all &&
              git reset --hard origin/dev &&
              git pull origin dev &&

              # Instalar dependencias necesarias
              pip install -r requirements.txt &&

              # Detener cualquier proceso que esté usando el puerto 5000
              sudo fuser -k 5000/tcp &&

              # Ejecutar la aplicación Flask
              nohup flask run --host=0.0.0.0 --port=5000 &

              # Desactivar el entorno virtual
              deactivate
              '
