name: DeployBackend

on:
  push:
    branches: [ "master" ]  # Cambiado a rama master

jobs:
  TestAndDeploy:
    name: Test and Deploy to EC2 Backend
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the master branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          cd paginaBigdataback &&
          pip install -r requirements.txt
          
      # Set PYTHONPATH and run unit tests
      - name: Run Unit Tests
        env:
          PYTHONPATH: ${{ github.workspace }}/paginaBigdataback
        run: |
          cd paginaBigdataback &&
          pytest tests/test_usuario.py --disable-warnings
          
      # Despliegue del Backend si las pruebas unitarias pasan
      - name: Deploy Backend to EC2 Instance
        if: success()  # Solo ejecutar si las pruebas pasan
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_HOST_BACK }}
          EC2_USER: ${{ secrets.USER_NAME }}
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
              cd /home/ubuntu/paginaBigdataback &&
              git fetch --all &&
              git reset --hard origin/master &&  # Cambiado a la rama master
              git pull origin master &&  # Cambiado a la rama master
              source /home/ubuntu/entornoGunicorn/bin/activate &&  # Usar entorno entornoGunicorn
              pip install -r requirements.txt &&
              fuser -k 5000/tcp || true &&
              tmux kill-session -t mysession || true &&  # Terminar sesión existente si existe
              tmux new-session -d -s mysession "gunicorn -b 0.0.0.0:5000 app:app > gunicorn.log 2>&1"
          '
